improvement

diff --git a/.github/actions/prepare-merge/action.yml b/.github/actions/prepare-merge/action.yml
--- a/.github/actions/prepare-merge/action.yml
+++ b/.github/actions/prepare-merge/action.yml
@@ -32,13 +32,21 @@ runs:
       shell: bash
 
     - name: Prepare pr with attempt to resolve conflicts
+      id: prepare-pr
       run: |
           # attempt to merge, check conflicts, if only in certain files, use $TARGET_BRANCH to resolve
           git fetch origin
           git checkout $SOURCE_BRANCH
+
           # do not use cutoff action, it breaks the history
-          git checkout -b $SOURCE_BRANCH-to-$TARGET_BRANCH
-          git merge --allow-unrelated-histories --verbose origin/$TARGET_BRANCH || true
+          TMP_BRANCH=$SOURCE_BRANCH-to-$TARGET_BRANCH
+          git branch -D $TMP_BRANCH || true
+          git push origin --delete "$TEMP_BRANCH" || true
+
+          git checkout -b $TMP_BRANCH
+          # rush bump to something that's in master
+          git merge --verbose origin/$TARGET_BRANCH || true
+
           # we are resolving only conflicts which we can do, we silently ignore other potential conflits
           conflicting_files=$(git diff --name-only --diff-filter=U | grep -E 'package.json|version-policies.json')
 
@@ -48,30 +56,23 @@ runs:
               git checkout --theirs $file
               git add $file
           done
-          git commit --no-verify -m "Resolved merge conflicts to match $TARGET_BRANCH"
-          git push origin $SOURCE_BRANCH-to-$TARGET_BRANCH
+
+          has_conflicts=false
+          conflicting_files=$(git diff --name-only --diff-filter=U)
+          if [ -n "$conflicting_files" ]; then
+            echo "There are conflicts which still need to be resolved, aborting"
+            has_conflicts=true
+            git merge --abort
+          else
+            git commit --no-verify -m "Resolved merge conflicts to match $TARGET_BRANCH"
+            git push origin $TMP_BRANCH
+          fi
+
+          PR_OUTPUT=$(gh pr create --title "Merge $SOURCE_BRANCH into $TARGET_BRANCH" --body "" --base $TARGET_BRANCH --head "$TMP_BRANCH")
+          PR_URL=$(echo "$PR_OUTPUT" | grep -o 'https://github.com[^ ]*')
+          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
+          echo "pr_has_conflicts=$has_conflicts" >> $GITHUB_OUTPUT
       env:
           SOURCE_BRANCH: ${{ inputs.source-branch }}
           TARGET_BRANCH: ${{ inputs.target-branch }}
       shell: bash
-
-    - uses: actions/github-script@v7
-      id: prepare-pr
-      env:
-          SOURCE_BRANCH: ${{ inputs.source-branch }}-to-${{ inputs.target-branch }}
-          TARGET_BRANCH: ${{ inputs.target-branch }}
-      with:
-        script: |
-          const { SOURCE_BRANCH, TARGET_BRANCH } = process.env
-
-          const response = await github.rest.pulls.create({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            title: `Merge ${SOURCE_BRANCH} into ${TARGET_BRANCH}`,
-            head: SOURCE_BRANCH,
-            base: TARGET_BRANCH,
-          });
-
-          const prUrl = response.data.html_url;
-          core.setOutput('pr-url', prUrl);
-        result-encoding: string
